import { exec } from '@actions/exec';
import { existsSync, readFileSync, readdirSync, renameSync } from 'fs';
import { join, resolve } from 'path';
import { info, step, endGroup, success } from './log';

export interface BundleArtifact {
  /** Absolute path to the file */
  path: string;
  /** Upload filename (basename) */
  name: string;
  /** Type of artifact */
  type: 'dmg' | 'archive' | 'signature' | 'installer' | 'updater-json';
}

export interface BuildResult {
  artifacts: BundleArtifact[];
  appVersion: string;
}

const TARGET_MAP: Record<string, string> = {
  'aarch64-apple-darwin': 'darwin-aarch64',
  'x86_64-apple-darwin': 'darwin-x86_64',
  'x86_64-pc-windows-msvc': 'windows-x86_64',
  'x86_64-unknown-linux-gnu': 'linux-x86_64',
  'aarch64-unknown-linux-gnu': 'linux-aarch64',
};

function archSuffix(target: string): string {
  if (target.includes('aarch64')) return 'aarch64';
  if (target.includes('x86_64')) return 'x86_64';
  return '';
}

export function targetToPlatform(target: string): string {
  const platform = TARGET_MAP[target];
  if (!platform) {
    throw new Error(`Unknown target: ${target}`);
  }
  return platform;
}

function findRunner(root: string): string {
  // Try to detect the package manager
  if (existsSync(join(root, 'pnpm-lock.yaml'))) return 'pnpm';
  if (existsSync(join(root, 'yarn.lock'))) return 'yarn';
  if (existsSync(join(root, 'bun.lockb'))) return 'bun';
  return 'npm';
}

export async function buildTauri(
  projectPath: string,
  target: string,
  privateKey: string,
  extraArgs: string,
): Promise<BuildResult> {
  const root = resolve(projectPath);
  if (!existsSync(join(root, 'src-tauri'))) {
    throw new Error(`No src-tauri directory found in ${root}`);
  }

  // Set up environment for signing
  const env: Record<string, string> = { ...process.env } as Record<string, string>;
  if (privateKey) {
    env['TAURI_PRIVATE_KEY'] = privateKey;
  }

  // Build
  const runner = findRunner(root);
  const cmd = runner === 'npm' ? 'npx' : runner;
  const execArgs = ['tauri', 'build', '--target', target];
  if (extraArgs) {
    execArgs.push(...extraArgs.split(/\s+/).filter(Boolean));
  }

  step(`Running: ${cmd} ${execArgs.join(' ')}`);
  const exitCode = await exec(cmd, execArgs, { cwd: root, env });
  endGroup();

  if (exitCode !== 0) {
    throw new Error(`Tauri build failed with exit code ${exitCode}`);
  }

  // Collect artifacts
  const bundleDir = join(root, 'src-tauri', 'target', target, 'release', 'bundle');
  if (!existsSync(bundleDir)) {
    throw new Error(`Bundle directory not found: ${bundleDir}`);
  }

  // Read app version from tauri.conf.json
  const tauriConfPath = join(root, 'src-tauri', 'tauri.conf.json');
  const tauriConf = JSON.parse(readFileSync(tauriConfPath, 'utf-8'));
  const appVersion = tauriConf.version || '';

  const artifacts: BundleArtifact[] = [];
  const platform = targetToPlatform(target);

  // Collect DMG (macOS only)
  const dmgDir = join(bundleDir, 'dmg');
  if (existsSync(dmgDir)) {
    const files = readdirSync(dmgDir).filter(f => f.endsWith('.dmg'));
    for (const f of files) {
      artifacts.push({ path: join(dmgDir, f), name: f, type: 'dmg' });
    }
  }

  // Collect MSI (Windows only)
  const msiDir = join(bundleDir, 'msi');
  if (existsSync(msiDir)) {
    const files = readdirSync(msiDir).filter(f => f.endsWith('.msi'));
    for (const f of files) {
      artifacts.push({ path: join(msiDir, f), name: f, type: 'installer' });
    }
  }

  const nsisDir = join(bundleDir, 'nsis');
  if (existsSync(nsisDir)) {
    const files = readdirSync(nsisDir).filter(f => f.endsWith('.exe'));
    for (const f of files) {
      artifacts.push({ path: join(nsisDir, f), name: f, type: 'installer' });
    }
  }

  // Collect appImage / deb (Linux only)
  const appImageDir = join(bundleDir, 'appimage');
  if (existsSync(appImageDir)) {
    const files = readdirSync(appImageDir).filter(f => f.endsWith('.AppImage'));
    for (const f of files) {
      artifacts.push({ path: join(appImageDir, f), name: f, type: 'installer' });
    }
  }
  const debDir = join(bundleDir, 'deb');
  if (existsSync(debDir)) {
    const files = readdirSync(debDir).filter(f => f.endsWith('.deb'));
    for (const f of files) {
      artifacts.push({ path: join(debDir, f), name: f, type: 'installer' });
    }
  }

  // Collect tar.gz archives and .sig files (macOS updater)
  const macosDir = join(bundleDir, 'macos');
  if (existsSync(macosDir)) {
    // Check if tar.gz already exists (generated by tauri build)
    let hasTarGz = readdirSync(macosDir).some(f => f.endsWith('.tar.gz'));
    if (!hasTarGz) {
      // Create it manually
      const appDir = readdirSync(macosDir).find(f => f.endsWith('.app'));
      if (appDir) {
        info(`Creating ${appDir}.tar.gz...`);
        const tarName = `${appDir}.tar.gz`;
        await exec('tar', ['czf', join(macosDir, tarName), '-C', macosDir, appDir], { cwd: macosDir });
        hasTarGz = true;
      }
    }

    if (hasTarGz) {
      for (const f of readdirSync(macosDir)) {
        if (f.endsWith('.tar.gz')) {
          let name = f;
          // Rename to include arch for matrix builds
          if (!name.includes('aarch64') && !name.includes('x86_64')) {
            const suffix = archSuffix(target);
            if (suffix) {
              name = name.replace('.app.tar.gz', `_${suffix}.app.tar.gz`);
              const oldPath = join(macosDir, f);
              const newPath = join(macosDir, name);
              renameSync(oldPath, newPath);
              info(`Renamed archive: ${f} → ${name}`);
            }
          }
          artifacts.push({ path: join(macosDir, name), name, type: 'archive' });
        }
        if (f.endsWith('.sig')) {
          let name = f;
          if (!name.includes('aarch64') && !name.includes('x86_64')) {
            const suffix = archSuffix(target);
            if (suffix) {
              name = name.replace('.app.tar.gz.sig', `_${suffix}.app.tar.gz.sig`);
              const oldPath = join(macosDir, f);
              const newPath = join(macosDir, name);
              renameSync(oldPath, newPath);
              info(`Renamed sig: ${f} → ${name}`);
            }
          }
          artifacts.push({ path: join(macosDir, name), name, type: 'signature' });
        }
      }
    }
  }

  success(`Collected ${artifacts.length} artifact(s)`);
  return { artifacts, appVersion };
}

export function readSignature(sigPath: string): string {
  const content = readFileSync(sigPath, 'utf-8').trim();
  return content;
}

export interface UpdateEntry {
  platform: string;
  signature: string;
  url: string;
}
